/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.ds.crawler;

import java.util.Scanner;

public class App {
    
    private static Scanner scanner = new Scanner(System.in);
    public static void main(String[] args) {
        SearcherThread searcherThread = new SearcherThread(args[0]);
        searcherThread.start();

        System.out.println("Press enter to interrupt the process.");
        scanner.nextLine();
        
        searcherThread.interrupt();
    }
}
